# Generated by Django 6.0.2 on 2026-03-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='Título del recordatorio')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Nota corta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='text',
            field=models.TextField(max_length=60),
        ),
    ]
