# Generated by Django 6.0.2 on 2026-03-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('EVALUATION', 'Evaluation'), ('SOCIAL', 'Social Event'), ('WORKSHOP', 'Workshop')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_modified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
