# Generated by Django 6.0.2 on 2026-03-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='category',
            field=models.CharField(choices=[('EVALUATION', 'Evaluation'), ('SOCIAL', 'Social Event'), ('WORKSHOP', 'Workshop')], max_length=15),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
