# Generated by Django 6.0.2 on 2026-03-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayudantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.CharField(max_length=100)),
                ('ayudante', models.CharField(max_length=100)),
                ('horarios', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.CharField(choices=[('CALCULO', 'Cálculo I/II'), ('FISICA', 'Fisica I/II'), ('BD', 'Base de Datos'), ('PROG', 'Programación')], max_length=50)),
                ('cantidad_estudiantes', models.PositiveIntegerField(default=1)),
                ('permitir_unirse', models.BooleanField(default=True)),
                ('fecha_limite', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(max_length=100)),
                ('ramos_que_domina', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tutor', models.CharField(max_length=150)),
                ('contacto', models.CharField(max_length=150)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='assistance.solicitudacademica')),
            ],
        ),
    ]
