# Generated by Django 6.0.2 on 2026-03-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudacademica',
            name='permitir_unirse',
        ),
        migrations.AddField(
            model_name='solicitudacademica',
            name='info_contacto',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OfertaTutor',
        ),
    ]
