# Generated by Django 6.0.2 on 2026-03-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Google Drive Recursos', max_length=100)),
                ('drive_url', models.URLField(help_text='Pega aquí el link compartido de Google Drive')),
            ],
        ),
    ]
